primary_readings_block = (('timestamp',
                                 'Volts A-N',
                                 'Volts B-N',
                                 'Volts C-N',
                                 'Volts A-B',
                                 'Volts B-C',
                                 'Volts C-A',
                                 'Amps A',
                                 'Amps B',
                                 'Amps C',
                                 'Watts 3-Ph total',
                                 'VARs 3-Ph total',
                                 'VAs 3-Ph total',
                                 'Power Factor 3-Ph total',
                                 'Frequency',
                                 'Neutral Current',
                                 'Watts Phase A',
                                 'Watts Phase B',
                                 'Watts Phase C',
                                 'VARs Phase A',
                                 'VARs, Phase B',
                                 'VARs Phase C',
                                 'VAs Phase A',
                                 'VAs Phase B',
                                 'VAs Phase C',
                                 'Power Factor Phase A',
                                 'Power Factor Phase B',
                                 'Power Factor Phase C',
                                 'Symmetrical Component Magnitude 0 Seq',
                                 'Symmetrical Component Magnitude + Seq',
                                 'Symmetrical Component Magnitude - Seq'))