primary_readings_block = (('timestamp',
                                 'Volts A-N',
                                 'Volts B-N',
                                 'Volts C-N',
                                 'Volts A-B',
                                 'Volts B-C',
                                 'Volts C-A',
                                 'Amps A',
                                 'Amps B',
                                 'Amps C',
                                 'Watts 3-Ph total',
                                 'VARs 3-Ph total',
                                 'VAs 3-Ph total',
                                 'Power Factor 3-Ph total',
                                 'Frequency',
                                 'Neutral Current'))